language: objective-c
osx_image: xcode9.2
gemfile: Gemfile

cache:
  - cocoapods
  - bundler

before_install:
  - bundle install
  - bundle exec pod install

script:
   - set -o pipefail
   - xcodebuild analyze test -workspace XCFKit.xcworkspace -scheme XCFKit -sdk iphonesimulator -destination "OS=11.2,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | bundle exec xcpretty -c
