source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'XCFKit Tests'
workspace '../XCFKit'

target 'Tests' do
  platform :ios, '8.0'
  pod 'Kiwi'
  pod 'XCFKit', :path => '../'

end
